apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.envVar.configmap.common }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{ if eq .Values.environment "dev" }}
  {{- range $key, $val := .Values.envVar.configmap.dev }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{ else if eq .Values.environment "test" }}
  {{- range $key, $val := .Values.envVar.configmap.test }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{ else if eq .Values.environment "preprod" }}
  {{- range $key, $val := .Values.envVar.configmap.preprod }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{ else if eq .Values.environment "prod" }}
  {{- range $key, $val := .Values.envVar.configmap.prod }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
