apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.application }}
  name: {{ .Values.route.name }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
  annotations:
    haproxy.router.openshift.io/timeout: 1m
spec:
  {{ if eq .Values.environment "dev" }}
  host: {{ .Values.route.dev.hostName }}
  {{ else if eq .Values.environment "test" }}
  host: {{ .Values.route.test.hostName }}
  {{ else if eq .Values.environment "preprod" }}
  host: {{ .Values.route.preprod.hostName }}
  {{ else if eq .Values.environment "prod" }}
  host: {{ .Values.route.prod.hostName }}
  {{ end }}
  port:
    targetPort: {{ .Values.service.port }}
  path: "/"
  to:
    kind: Service
    name: {{ .Values.service.name }}-{{ .Values.environment }}
    weight: 100
  wildcardPolicy: None

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.application }}
  name: {{ .Values.route.name }}-{{ .Values.environment }}-https
  namespace: {{ .Release.Namespace }}
  annotations:
    haproxy.router.openshift.io/timeout: 1m
    cert-utils-operator.redhat-cop.io/certs-from-secret: star-test-finagotech.crt
spec:
  {{ if eq .Values.environment "dev" }}
  host: {{ .Values.route.dev.hostNameHttps }}
  {{ else if eq .Values.environment "test" }}
  host: {{ .Values.route.test.hostNameHttps }}
  {{ else if eq .Values.environment "preprod" }}
  host: {{ .Values.route.preprod.hostNameHttps }}
  {{ else if eq .Values.environment "prod" }}
  host: {{ .Values.route.prod.hostNameHttps }}
  {{ end }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    enabled: true
    termination: "edge"
    insecureEdgeTerminationPolicy: "Redirect"
    key: ""
    certificate: ""
  to:
    kind: Service
    name: {{ .Values.service.name }}-{{ .Values.environment }}
    weight: 100
  wildcardPolicy: None
