apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.envVar.secret.common }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{ if eq .Values.environment "dev" }}
  {{- range $key, $val := .Values.envVar.secret.dev }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{ else if eq .Values.environment "test" }}
  {{- range $key, $val := .Values.envVar.secret.test }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{ else if eq .Values.environment "preprod" }}
  {{- range $key, $val := .Values.envVar.secret.preprod }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{ else if eq .Values.environment "prod" }}
  {{- range $key, $val := .Values.envVar.secret.prod }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}